# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Личный блог Алины Готовцевой.
description: > # this means to ignore newlines until "baseurl:"
  Немного про то, как и чему я учусь каждый (почти) день.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://alinakago.ru" # the base hostname & protocol for your site
email: info@alinakago.ru
github_username:  alinaka
vk_username: alinakago
timezone: Europe/Moscow

# Build settings
markdown: kramdown
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
